name: Test Documentation
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  docs:
    name: Test documentation
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Install Minari
        run: pip install .[testing]

      - name: Build Datasets Docs
        run: python docs/_scripts/gen_dataset_md.py

      - name: Build
        run: sphinx-build -b dirhtml -v docs _build

      - name: Move 404
        run: mv _build/404/index.html _build/404.html

      - name: Update 404 links
        run: python docs/_scripts/move_404.py _build/404.html

      - name: Remove .doctrees
        run: rm -r _build/.doctrees

      - name: Run documentation tests
        run: xvfb-run -s "-screen 0 1024x768x24" pytest docs --markdown-docs -m markdown-docs
